eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://one-health-yjb-yjb28-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/eureka